version: '3'

volumes:
  mongo:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
     - mongo:/data/db
    ports:
      - "27017:27017"
      
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
     - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    ports:
     - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo.rule=Host(`mongo.${HOST}`)"
      - "traefik.http.routers.mongo.entrypoints=websecure"
      - "traefik.http.routers.mongo.tls.certresolver=myresolver"
